USE [master]
GO

/****** Object:  Database [LibraryDB]    Script Date: 15.11.2020 21:46:54 ******/
CREATE DATABASE [LibraryDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LibraryDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\LibraryDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LibraryDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\LibraryDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LibraryDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LibraryDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LibraryDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LibraryDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LibraryDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LibraryDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [LibraryDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LibraryDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [LibraryDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LibraryDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LibraryDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LibraryDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LibraryDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LibraryDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LibraryDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LibraryDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LibraryDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LibraryDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LibraryDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LibraryDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LibraryDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LibraryDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LibraryDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LibraryDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LibraryDB] SET RECOVERY FULL 
GO

ALTER DATABASE [LibraryDB] SET  MULTI_USER 
GO

ALTER DATABASE [LibraryDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LibraryDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LibraryDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LibraryDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LibraryDB] SET  READ_WRITE 
GO



USE [LibraryDB]
GO

/****** Object:  Table [dbo].[Book]    Script Date: 15.11.2020 21:46:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Book](
	[BookID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](max) NULL,
	[Author] [nvarchar](max) NULL,
	[PublishmentYear] [int] NULL,
	[ShortDescription] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[BookID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

/****** Object:  Table [dbo].[Reservation]    Script Date: 15.11.2020 21:46:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Reservation](
	[ReservationID] [int] IDENTITY(1,1) NOT NULL,
	[ReservationDate] [date] NOT NULL,
	[UserID] [int] NULL,
	[BookID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ReservationID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Reservation]  WITH CHECK ADD FOREIGN KEY([BookID])
REFERENCES [dbo].[Book] ([BookID])
GO

